woorifisa-projects/HaeDal

- .idea/inspectionProfiles/Project_Default.xml
- backend/src/main/java/com/haedal/backend/admin/controller/AdminController.java
- backend/src/main/java/com/haedal/backend/admin/dto/request/AdminRequest.java
- backend/src/main/java/com/haedal/backend/admin/dto/response/AdminResponse.java
- backend/src/main/java/com/haedal/backend/admin/model/Admin.java
- backend/src/main/java/com/haedal/backend/admin/repository/AdminRepository.java
- backend/src/main/java/com/haedal/backend/admin/service/AdminService.java
- backend/src/main/java/com/haedal/backend/auth/controller/AuthController.java
- backend/src/main/java/com/haedal/backend/auth/dto/request/AuthRequest.java
- backend/src/main/java/com/haedal/backend/auth/dto/response/AuthResponse.java
- backend/src/main/java/com/haedal/backend/auth/model/Auth.java
- backend/src/main/java/com/haedal/backend/common/service/CrudService.java
- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/dto/request/ProductRequest.java
- backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
- backend/src/main/java/com/haedal/backend/product/model/Product.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/product/service/ProductService.java
- backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
- backend/src/main/java/com/haedal/backend/profile/dto/request/ProfileRequest.java
- backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
- backend/src/main/java/com/haedal/backend/profile/model/User.java
- backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
> Chore : 백엔드 패키지 구조 설정

- backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
- backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
- backend/src/main/java/com/haedal/backend/profile/model/ServicePurpose.java
- backend/src/main/java/com/haedal/backend/profile/model/User.java
- backend/src/main/java/com/haedal/backend/profile/model/UserAgeGroup.java
- backend/src/main/java/com/haedal/backend/profile/repository/ProfileRepository.java
- backend/src/main/java/com/haedal/backend/profile/service/CrudService.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
- backend/src/main/resources/application.properties
> Feat : 프로필 Api

- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/model/Deposit.java
- backend/src/main/java/com/haedal/backend/product/model/InstallmentSavings.java
- backend/src/main/java/com/haedal/backend/product/model/Product.java
- backend/src/main/java/com/haedal/backend/product/model/Subscribe.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/profile/model/Account.java
- backend/src/main/java/com/haedal/backend/profile/model/User.java
- backend/src/test/java/com/haedal/backend/product/ProductControllerTest.java
DB 리팩토링 했습니다 
[추가내용]
- Account 테이블 생성했습니다
- Desposit, InstallmentSavings 테이블 생성했습니다
- User 테이블에 필드값 수정되었습니다.
> Refactor : DB 리팩토링

- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/dto/request/ProductRequest.java
- backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
- backend/src/main/java/com/haedal/backend/product/model/Product.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/product/service/CrudService.java
- backend/src/main/java/com/haedal/backend/product/service/ProductService.java
- backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
- backend/src/main/resources/application.properties
- frontend/package-lock.json
- frontend/package.json
[추가기능]
ProductController 생성 후, 각 태그별 필터링 기능 구현했습니다
[보완점]
Controller단에서 PostResponse 객체를 받아오는 기능을 구현하지 못해 에러가 발생했습니다. 추후 수정하겠습니다
> Feature : 전체상품 조회, 필터링 기능 구현

- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/product/service/ProductService.java
- backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
- frontend/src/App.vue
- frontend/src/router/index.js
- frontend/src/views/ProductList.vue
- 상품 키워드 검색 기능 추가
- ProductResponse 수정
- productService, ProductRepository 기능 추가
> feature : 상품 키워드 검색 기능 추가

- backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
[Refactor]
- PostService에서 findAll() 리턴 값 수정
- SecurityConfig에서 "/products/**" 접근 허용
> Refactor : 접근권한 허용 - /products/

- backend/src/main/java/com/haedal/backend/auth/service/UserService.java
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/views/Header.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/SignUpView.vue
화면 UI 개발시 필요한 의존성 설치 및 헤더, 로그인, 회원가입 화면 1차 구현
> Style : 헤더,로그인,회원가입화면 구현

- backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
이름 검색 post api 수정
- security에 products/** permit 외에, product/{search}를 추가
(위를 작성 하지 않으면 또 403에러 발생)
- controller url과 예외처리 추가
> refactor : 제품 이름 검색 기능 수정

- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
[Refactor]
- ProductService탭에서 return 값을 ProductRepository.findByTag()로 수정, Tag기준 필터링 기능 구현했습니다
> Refactor : 상품탭 필터링 기능 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/views/Header.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/SignUpView.vue
> Style : 로그인,회원가입 화면 구현

- backend/src/main/java/com/haedal/backend/auth/model/User.java
- backend/src/main/java/com/haedal/backend/product/model/Deposit.java
- backend/src/main/java/com/haedal/backend/product/model/InstallmentSavings.java
- backend/src/main/java/com/haedal/backend/product/model/Product.java
- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- backend/src/main/java/com/haedal/backend/subscribe/dto/response/SubscribeResponse.java
- backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
- backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
- backend/src/main/java/com/haedal/backend/subscribe/service/CrudService.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
- subscribe 패키지 구조 설정
- subscribe 모델 수정
- subscribe controller  초안 설정
> feature : 구독 model 수정, 패키지 설정, controller 기능 초안 설정

- backend/src/main/java/com/haedal/backend/product/model/Product.java
[수정사항]
- Desposit, InstallmentSavings 엔티티 삭제
- Product 테이블에 'boolean isDeposit(0=예금, 1=적금)' 필드값 추가
- Product 테이블에 'int subscription' 필드값 추가
> Refactor : Product DB 수정 - 예금,적금 테이블 삭제 후 통합테이블 구현

- backend/src/main/java/com/haedal/backend/auth/dto/request/UserRegisterRequest.java
- backend/src/main/java/com/haedal/backend/auth/service/UserService.java
- backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
- backend/src/test/java/com/haedal/backend/auth/service/UserServiceTest.java
> Feature : 회원가입, 로그인 service 단계 테스트 코드 작성

- backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
- backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
- backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- 이용목적 기준 상품 필터링 기능 수정
TODO
- 연령별, 자산별 필터링 수정 (현재 주석처리)
> fix : 상품 추천 필터 api 수정

- backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
- backend/src/main/java/com/haedal/backend/product/service/ProductServiceImpl.java
- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- frontend/src/views/RecommendedProduct.vue
ProductServiceImp의 return null로 인한 get요청 에러 수정
> refactor : get요청 nullPointException 해결, serviceImp 수정

- backend/src/test/java/com/haedal/backend/auth/service/UserServiceTest.java
- userService 테스트 코드 false 수정
TODO
- 원하는 대로 테스트코드 재작성
> fix : userService 테스트코드 error 수정

- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
- backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/product/service/RecommendedProductService.java
- backend/src/main/java/com/haedal/backend/product/service/RecommendedProductServiceImpl.java
- backend/src/main/java/com/haedal/backend/profile/model/UserAgeGroup.java
- backend/src/main/resources/application.properties
[추가사항]
- servicePurpose, userAgeGroup 카테고리 API기능 추가
[수정사항]
- userAgeGroup에 'ONETWOTHREEFOURFIVE'라는 전연령대 필드 추가
- userAgeGroup에 contains()를 활용
- 이해가 편하도록 메서드명, 변수명 수정
> Feature: 추천상품 조회기능 API 기능 추가 및 수정

- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- frontend/src/components/ProfileNavigationBar.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/router/index.js
- frontend/src/views/LoginView.vue
- frontend/src/views/MainPage.vue
- frontend/src/views/MyPage.vue
- frontend/src/views/ProductList.vue
- frontend/src/views/SignUpView.vue
회원상품가입 api 로그인정보와 연동하여 개발 및 화면 요청 부분 수정
> Refactor : 회원상품가입 api 로그인정보와 연동하여 개발 및 화면 요청 부분 수정

- frontend/src/views/RecommendedProduct.vue
[done]
추천상품탭의 프론트, 백엔드 통신 연결완료했습니다
> refactor : recommendedProduct API connection

- frontend/src/components/ProfileNavigationBar.vue
- frontend/src/layouts/default/AppBar.vue
- frontend/src/layouts/default/Default.vue
- frontend/src/router/index.js
- frontend/src/views/MainPage.vue
- frontend/src/views/MyPage.vue
- frontend/src/views/ProductList.vue
- frontend/src/views/RecommendedProduct.vue
- frontend/src/views/SubscribeD.vue
- frontend/src/views/SubscribeI.vue
- frontend/src/views/SubscribeSuccess.vue
- frontend/src/views/UserProfileEdit.vue
- products UI 수정 
- 검색 결과가 없을 시 문구 노출
- 성공화면 UI 제작, url 연결
- recommended products ui 수정
> style : 상품 관련 ui 정리

- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- backend/src/main/java/com/haedal/backend/subscribe/dto/response/PortfolioResponse.java
- backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
- backend/src/main/java/com/haedal/backend/subscribe/service/CrudService.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
- frontend/src/components/ProfileNavigationBar.vue
- frontend/src/router/index.js
- frontend/src/views/LoginView.vue
- frontend/src/views/MyPage.vue
- frontend/src/views/Portfolio.vue
- frontend/src/views/SubscribeDforShow.vue
- frontend/src/views/SubscribeIforShow.vue
- frontend/src/views/UserProfileEdit.vue
> [Feature] 포트폴리오 api 개발 및 상품 조회 화면 추가

- backend/src/main/java/com/haedal/backend/product/dto/response/ProductResponse.java
- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- frontend/src/router/index.js
- frontend/src/views/ProductList.vue
- frontend/src/views/SubscribeD.vue
- frontend/src/views/SubscribeI.vue
- 사용자의 정보, 상품 정보 조회하는 기능 controller에서 response로 구조 리팩토링
- 프론트 success router 수정
- 프론트 검색 상품이 없을 경우 나타나는 문자 표출 관련 함수 추가 / set timeout 설정
- 상품 신청 부분 - 금액 입력 후 '만기시 금액' 클릭시, 최대 금액보다 크면 이에 매한 메세지 설정
라우터 수정 전 (default 내부)
라우터 수정 후(default 외부)
단독 페이지처럼 보이게 합니다!
> refactor : controller의 dto 프로세스 리팩토링

- backend/src/main/java/com/haedal/backend/auth/model/User.java
- backend/src/main/java/com/haedal/backend/product/controller/ProductController.java
- backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
- backend/src/main/java/com/haedal/backend/product/model/Product.java
- frontend/src/views/ProductList.vue
- frontend/src/views/RecommendedProduct.vue
-  product_status 칼럼 추가
- user_status 칼럼 추가
(모든 status의 기본값은 1, 관리자가 이것을 0으로 바꿀 수 있다.) 
- product controller 설정 수정
> 고객은 status가 1인 상품들만 조회할 수 있다.
- recommend controller 설정 수정
> 추천 상품은 status가 1인 상품들만 조회될 수 있다.
- recommend 클라이언트, 서버 인증관련 설정 추가
클라이언트의 요청들이 모두 localhost:8080으로 되어있다.
추후 수정 필요.
> feature : status 칼럼 추가, 관련 로직 수정, 상품추천 인증 설정 추가

- backend/src/main/java/com/haedal/backend/product/controller/RecommendedProductController.java
- frontend/src/components/ProfileNavigationBar.vue
- frontend/src/views/Portfolio.vue
- frontend/src/views/PortfolioDays.vue
- frontend/src/views/Portfoliodibs.vue
포트폴리오 화면 클릭시 router로 이동부분 추가 및 코드 리팩토링 추가
> Refactor : 포트폴리오 화면 클릭시 router로 이동부분 추가

- frontend/src/layouts/default/AppBar.vue
- frontend/src/views/LoginView.vue
도메인을 이용해 HTTPS로 변경후 로그인통신이 정상적으로 이루어지는지 확인한다
> Feature : HTTPS를 적용한다

- backend/src/main/java/com/haedal/backend/auth/config/JwtFilter.java
- backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
- backend/src/main/java/com/haedal/backend/auth/model/User.java
- backend/src/main/java/com/haedal/backend/product/repository/ProductRepository.java
- backend/src/main/java/com/haedal/backend/subscribe/model/Subscribe.java
- backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
- frontend/src/layouts/default/AppBar.vue
- frontend/src/views/LoginView.vue
> Refactor : 유저 회원탈퇴 관련 api 수정, 로그인시 회원상태에 따라 분기처리

- backend/build.gradle
- backend/src/docs/asciidoc/auth.adoc
- backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
- backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
- backend/src/main/java/com/haedal/backend/auth/dto/response/UserLoginResponse.java
- backend/src/main/java/com/haedal/backend/auth/service/UserService.java
- backend/src/main/java/com/haedal/backend/sms/dto/MessageDTO.java
- backend/src/main/resources/static/auth.html
- backend/src/main/resources/static/index.html
- backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
- backend/src/test/java/com/haedal/backend/common/ControllerTest.java
- frontend/src/layouts/default/AppBar.vue
- frontend/src/views/LoginView.vue
RestDocs 의존성 설치 및 공통TestCode 추가 및 UserController Test코드 작성
> Feature  RestDocs 의존성 설치 및 공통TestCode 추가 및 UserController Test코드 작성 

- backend/src/main/java/com/haedal/backend/auth/controller/UserController.java
- backend/src/main/java/com/haedal/backend/auth/model/User.java
- backend/src/main/java/com/haedal/backend/auth/service/UserService.java
- frontend/src/views/LoginView.vue
- 고객 가입시 상태를 1로 설정해준다.
- updateUserStatus 메서드 수정
> refactor : 고객 가입시 상태 true로 설정

- backend/src/main/java/com/haedal/backend/subscribe/controller/SubscribeController.java
- backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeService.java
- backend/src/main/java/com/haedal/backend/subscribe/service/SubscribeServiceImp.java
- frontend/src/views/SubscribeDforShow.vue
- frontend/src/views/SubscribeIforShow.vue
> Feature 포트폴리오 내에서 구독한 상품 해지 api와 화면을 개발한다

- backend/src/main/java/com/haedal/backend/auth/service/UserService.java
- backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
- backend/src/test/java/com/haedal/backend/common/ControllerTest.java
- frontend/src/layouts/default/AppBar.vue
> Feat : appbar 로그인만료시간 체크추가

- frontend/src/views/LoginView.vue
> test : 테스트용 경로 수정

- backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
- backend/src/main/java/com/haedal/backend/subscribe/repository/SubscribeRepository.java
상품구독해제 시 jpql 쿼리문 명확하게 리팩토링 진행
> refactor : 상품구독해제 시 jpql 쿼리문 명확하게 리팩토링 진행

- backend/src/main/java/com/haedal/backend/auth/dto/request/UserPasswordCheckRequest.java
- backend/src/main/java/com/haedal/backend/auth/dto/request/UserUpdateRequest.java
- backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
- backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
- backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
- backend/src/test/java/com/haedal/backend/product/ProductControllerTest.java
- backend/src/test/java/com/haedal/backend/profile/controller/ProfileControllerTest.java
profile 단위테스트 코드 작성 및 ProfileController 코드 리팩토링
> feat : profile 단위테스트 코드 작성 및 ProfileController 코드 리팩토링

- backend/src/main/java/com/haedal/backend/auth/dto/request/UserPasswordCheckRequest.java
- backend/src/main/java/com/haedal/backend/auth/dto/request/UserUpdateRequest.java
- backend/src/main/java/com/haedal/backend/profile/controller/ProfileController.java
- backend/src/main/java/com/haedal/backend/profile/dto/response/ProfileResponse.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileService.java
- backend/src/main/java/com/haedal/backend/profile/service/ProfileServiceImpl.java
- backend/src/test/java/com/haedal/backend/auth/controller/UserControllerTest.java
- backend/src/test/java/com/haedal/backend/product/ProductControllerTest.java
- backend/src/test/java/com/haedal/backend/profile/controller/ProfileControllerTest.java
> Test : profile 기능 리팩토링 및 test코드 작성

- backend/src/main/java/com/haedal/backend/auth/config/SecurityConfig.java
- frontend/src/router/index.js
- frontend/src/views/ForPasswordChange.vue
- frontend/src/views/ForSecuritySetting.vue
- frontend/src/views/LoginView.vue
- frontend/src/views/SignUpView.vue
> refactor : 회원가입-UI수정, ID중복체크 실패시 예외모달창 추가

- frontend/src/views/LoginView.vue
- frontend/src/views/SignUpView.vue
비밀번호 visible이벤트 발생시 바로 출력안되는 문제 수정
> fix : 비밀번호 visible이벤트 발생시 바로 출력안되는 문제 수정

- frontend/package-lock.json
- frontend/package.json
- frontend/src/views/Test.vue
> chore : chartJS 환경설정

- frontend/src/views/Portfoliodibs.vue
- frontend/src/views/ProductList.vue
- frontend/src/views/RecommendedProduct.vue
- frontend/src/views/SubscribeD.vue
- frontend/src/views/SubscribeI.vue
- frontend/src/views/SubscribeSuccess.vue
- frontend/src/views/UserLeave.vue
> refactor : img태그에 alt 속성 추가
